export const demoNGOs = [
  {
    ngo_id: 1,
    login_id: "hope_foundation@sdgplatform.com",
    password: "HopeFound2024!",
    name: "Hope Foundation",
    email: "contact@hopefoundation.org",
    phone: "+1-555-0123",
    country: "United States",
    state: "California",
    city: "San Francisco",
    address: "123 Hope Street, San Francisco, CA 94105",
    sector: ["Education", "Poverty"],
    unique_id: "HF123456",
    verification_documents: {},
    verification_status: "Approved",
    operational_status: "Active",
    projects: [
      {
        project_id: 1,
        title: "Digital Literacy Program",
        project_type: "EDUCATION",
        description: "Teaching basic computer skills to underprivileged youth",
        required_skills: ["Teaching", "Computer Science", "Communication"],
        commitment_type: "Physical",
        country: "United States",
        state: "California",
        city: "San Francisco",
        safe_for_women: true,
        progress_parameters: ["Setup curriculum", "Train teachers", "Complete first batch"],
        progress_updates: ["Setup curriculum"],
        volunteer_accepted: ["vol_1", "vol_3"],
        volunteers_requests: [],
        funding_requirements: 5000,
        created_at: "2024-01-15T00:00:00.000Z",
        updated_at: "2024-02-15T00:00:00.000Z"
      }
    ],
    number_volunteers_taken: 2,
    review: [],
    un_ecosoc: "YES",
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    ngo_id: 2,
    login_id: "green_earth@sdgplatform.com",
    password: "GreenEarth2024!",
    name: "Green Earth Initiative",
    email: "info@greenearth.org",
    phone: "+1-555-0456",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    address: "456 Green Street, Toronto, ON M5V 2H1",
    sector: ["Environment", "Health"],
    unique_id: "GE789012",
    verification_documents: {},
    verification_status: "Approved",
    operational_status: "Active",
    projects: [
      {
        project_id: 2,
        title: "Urban Garden Project",
        project_type: "ENVIRONMENT",
        description: "Creating sustainable urban gardens in local communities",
        required_skills: ["Gardening", "Community Outreach", "Project Management"],
        commitment_type: "Physical",
        country: "Canada",
        state: "Ontario",
        city: "Toronto",
        safe_for_women: true,
        progress_parameters: ["Site selection", "Community engagement", "Garden setup", "First harvest"],
        progress_updates: ["Site selection", "Community engagement"],
        volunteer_accepted: ["vol_2", "vol_5", "vol_7"],
        volunteers_requests: [],
        funding_requirements: 7500,
        created_at: "2024-01-20T00:00:00.000Z",
        updated_at: "2024-02-15T00:00:00.000Z"
      }
    ],
    number_volunteers_taken: 3,
    review: [],
    un_ecosoc: "NO",
    created_at: "2024-01-15T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  }
];

export const demoVolunteers = [
  {
    volunteer_id: "vol_1",
    login_id: "john.smith@volunteer.org",
    password: "JohnSmith2024!",
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "+1-555-1234",
    country: "United States",
    state: "New York",
    city: "New York City",
    skills: ["Web Development", "Project Management", "Teaching"],
    interests: ["Education", "Technology"],
    availability: "Part-time",
    projects_joined: [1],
    impact_score: 85,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_2",
    login_id: "emma.wilson@volunteer.org",
    password: "EmmaWilson2024!",
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    phone: "+44-555-5678",
    country: "United Kingdom",
    state: "England",
    city: "London",
    skills: ["Environmental Science", "Community Outreach", "Research"],
    interests: ["Environment", "Sustainability"],
    availability: "Full-time",
    projects_joined: [2],
    impact_score: 92,
    created_at: "2024-01-15T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_3",
    login_id: "maria.garcia@volunteer.org",
    password: "MariaGarcia2024!",
    name: "Maria Garcia",
    email: "maria.garcia@example.com",
    phone: "+34-555-9012",
    country: "Spain",
    state: "Madrid",
    city: "Madrid",
    skills: ["Teaching", "Language Skills", "Cultural Exchange"],
    interests: ["Education", "Cultural Integration"],
    availability: "Part-time",
    projects_joined: [1],
    impact_score: 78,
    created_at: "2024-01-20T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_4",
    login_id: "alex.chen@volunteer.org",
    password: "AlexChen2024!",
    name: "Alex Chen",
    email: "alex.chen@example.com",
    phone: "+86-555-3456",
    country: "China",
    state: "Shanghai",
    city: "Shanghai",
    skills: ["Data Analysis", "Project Coordination", "Marketing"],
    interests: ["Technology", "Education"],
    availability: "Full-time",
    projects_joined: [],
    impact_score: 70,
    created_at: "2024-01-25T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_5",
    login_id: "sarah.kumar@volunteer.org",
    password: "SarahKumar2024!",
    name: "Sarah Kumar",
    email: "sarah.kumar@example.com",
    phone: "+91-555-7890",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    skills: ["Community Development", "Healthcare", "Project Management"],
    interests: ["Health", "Community Welfare"],
    availability: "Part-time",
    projects_joined: [2],
    impact_score: 88,
    created_at: "2024-01-30T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_6",
    login_id: "david.mueller@volunteer.org",
    password: "DavidMueller2024!",
    name: "David Mueller",
    email: "david.mueller@example.com",
    phone: "+49-555-2345",
    country: "Germany",
    state: "Berlin",
    city: "Berlin",
    skills: ["Engineering", "Renewable Energy", "Technical Training"],
    interests: ["Environment", "Technology"],
    availability: "Full-time",
    projects_joined: [],
    impact_score: 82,
    created_at: "2024-02-01T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_7",
    login_id: "aisha.patel@volunteer.org",
    password: "AishaPatel2024!",
    name: "Aisha Patel",
    email: "aisha.patel@example.com",
    phone: "+1-555-4567",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    skills: ["Urban Planning", "Sustainability", "Community Engagement"],
    interests: ["Environment", "Urban Development"],
    availability: "Part-time",
    projects_joined: [2],
    impact_score: 90,
    created_at: "2024-02-05T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_8",
    login_id: "carlos.santos@volunteer.org",
    password: "CarlosSantos2024!",
    name: "Carlos Santos",
    email: "carlos.santos@example.com",
    phone: "+55-555-8901",
    country: "Brazil",
    state: "São Paulo",
    city: "São Paulo",
    skills: ["Social Work", "Youth Development", "Sports Coaching"],
    interests: ["Education", "Youth Empowerment"],
    availability: "Full-time",
    projects_joined: [],
    impact_score: 75,
    created_at: "2024-02-10T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_9",
    login_id: "sophie.dubois@volunteer.org",
    password: "SophieDubois2024!",
    name: "Sophie Dubois",
    email: "sophie.dubois@example.com",
    phone: "+33-555-6789",
    country: "France",
    state: "Île-de-France",
    city: "Paris",
    skills: ["Art Education", "Cultural Programs", "Event Management"],
    interests: ["Education", "Arts"],
    availability: "Part-time",
    projects_joined: [],
    impact_score: 80,
    created_at: "2024-02-12T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    volunteer_id: "vol_10",
    login_id: "james.wilson@volunteer.org",
    password: "JamesWilson2024!",
    name: "James Wilson",
    email: "james.wilson@example.com",
    phone: "+61-555-0123",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
    skills: ["Digital Marketing", "Content Creation", "Social Media"],
    interests: ["Technology", "Communication"],
    availability: "Full-time",
    projects_joined: [],
    impact_score: 73,
    created_at: "2024-02-14T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  }
];