export const demoNGOs = [
  {
    ngo_id: 1,
    login_id: "hope_foundation@sdgplatform.com",
    password: "HopeFound2024!",
    name: "Hope Foundation",
    email: "contact@hopefoundation.org",
    phone: "+1-555-0123",
    country: "United States",
    state: "California",
    city: "San Francisco",
    address: "123 Hope Street, San Francisco, CA 94105",
    sector: ["Education", "Poverty"],
    unique_id: "HF123456",
    verification_documents: {},
    verification_status: "Approved",
    operational_status: "Active",
    projects_posted: 3,
    number_volunteers_taken: 45,
    review: [],
    un_ecosoc: "YES",
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  },
  {
    ngo_id: 2,
    login_id: "green_earth@sdgplatform.com",
    password: "GreenEarth2024!",
    name: "Green Earth Initiative",
    email: "info@greenearth.org",
    phone: "+1-555-0456",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    address: "456 Green Street, Toronto, ON M5V 2H1",
    sector: ["Environment", "Health"],
    unique_id: "GE789012",
    verification_documents: {},
    verification_status: "Approved",
    operational_status: "Active",
    projects_posted: 5,
    number_volunteers_taken: 72,
    review: [],
    un_ecosoc: "NO",
    created_at: "2024-01-15T00:00:00.000Z",
    updated_at: "2024-02-15T00:00:00.000Z"
  }
];